import { Container } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import TopNav from 'components/TopNav'
import { GeistSans } from 'geist/font/sans'
import theme from 'lib/theme'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Number 9',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={GeistSans.className}>
        <NextTopLoader color='#D14124' />
        <Toaster
          position='top-center'
          toastOptions={{
            style: { padding: '16px' },
            success: {
              style: { color: 'white', background: '#43a047' },
              iconTheme: { primary: 'white', secondary: '#43a047' },
            },
            error: {
              style: { color: 'white', background: '#d32f2f' },
              iconTheme: { primary: 'white', secondary: '#d32f2f' },
            },
          }}
        />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <TopNav />

            <Container maxWidth='md' component='main' sx={{ pt: 4 }}>
              {children}
            </Container>
          </ThemeProvider>
        </AppRouterCacheProvider>{' '}
      </body>
    </html>
  )
}
